usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/audio/audio
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/chartsgallery/chartsgallery
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/openglseries/openglseries
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/qmlchartsgallery/qmlchartsgallery
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/qmloscilloscope/qmloscilloscope
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/qmlweather/qmlweather
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/charts/zoomlinechart/zoomlinechart
